# Services for the Studer-Xcom integration

get_message:
  "description": "Retrieve the latest or historic messages from Studer-Innotec devices"
  # The target allows filtering the scope of the service call
  #target:
  #  config_entry:
  #    integration: studer_xcom
  # Fields the service accepts, besides the target
  fields:
    index:
      required: true
      advanced: false
      example: 0
      default: 0
      selector:   # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
        number:
          min: 0
